### ISSUE TITLE
User Acceptance Scenario

### ISSUE THREAD

**Issue by AlexzPurewoko** [dicoding-dev/abilities-php#1]
## Acceptance Scenario Test

   PASS  Tests\Feature\Core\AbilityCheckerImplTest
  ✓ can() feature function test → it must return false when the user have inverted rule
  ✓ can() feature function test → it must return true when user have rule with ALL action
  ✓ can() feature function test → it must return true when the rule is matched with user abilities
  ✓ can() feature function test → it must return false when the rule is unmatched with user abilities
  ✓ cannot() feature function test → it must return true when the user cannot access the resource
  ✓ hasRule() feature function test → it must return true when the rule exactly found on the user abilities
  ✓ hasRule() feature function test → it must return false when the rule is not found on the user abilities

   PASS  Tests\Feature\Core\Repository\AbilityRepositoryImplTest
  ✓ Get Ability Checker Function Test → it must return ability checker…  0.01s  
  ✓ Add ability test → it must not add the ability when the user has the rule
  ✓ Add ability test → it must add the ability when the user doesnt have the rule
  ✓ Add ability test → it can add many rules
  ✓ Remove the ability test → it cannot delete when the ability doesnt exist
  ✓ Remove the ability test → it can remove the ability
  ✓ Remove the ability test → it can remove many abilities
  ✓ Update the ability rule test → it cannot update the ability when the ability doesnt exist
  ✓ Update the ability rule test → it can update the ability

   PASS  Tests\Unit\Core\Objects\ActionTest
  ✓ it must fail when assigned with empty value                          0.01s  
  ✓ Must use star symbol when using default argument
  ✓ Successfully define specific action

   PASS  Tests\Unit\Core\Objects\CompiledRulesTest
  ✓ Compile and query rules → it must return empty if scope does not found with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return empty if resource does not found with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return empty if action does not found with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return expected rule id with (Abilities\Core\Objects\CompiledRules)

   PASS  Tests\Unit\Core\Objects\ResourceTest
  ✓ it must throw error when passing empty/blank argument on 'resource'
  ✓ toString function test → successfully encode without field
  ✓ toString function test → successfully encode with array field
  ✓ toString function test → successfully encode with json object field
  ✓ toString function test → successfully encode with non json field
  ✓ allField() function test → it must return true when field property is empty
  ✓ allField() function test → it must return true when field property is star
  ✓ allField() function test → it must return false when field property is neither star and empty
  ✓ matchField() function test → it must return true if the resource rule has star field
  ✓ matchField() function test → it must return false if the argument is empty
  ✓ matchField() function test → it must return true if match the single field
  ✓ matchField() function test → it must return false if fields does not contains the field argument
  ✓ matchField() function test → it must return true if fields contains the field argument
  ✓ matchField() function test → it must return true if fields contains exactly one field argument
  ✓ matchField() function test → it must return true if field object match exactly with argument
  ✓ matchField() function test → it must return false if field object doesnt match exactly with argument

   PASS  Tests\Unit\Core\Objects\RuleTest
  ✓ getRuleId function test → it must throw error when not calling setRuleId beforehand
  ✓ getRuleId function test → it returns expected ruleId
  ✓ toString function test → successfully encode inverted rules
  ✓ toString function test → successfully encode normal rules
  ✓ toString function test → successfully rule with custom resource

   PASS  Tests\Unit\Core\Objects\ScopeTest
  ✓ it must throw error when passing empty/blank argument on 'scope'
  ✓ Must use 'global' when using default argument
  ✓ Successfully define specific action

   PASS  Tests\Unit\Core\RuleCompilerTest
  ✓ Compile a rule syntax → it must throw error if syntax is empty
  ✓ Compile a rule syntax → it must throw error if scope is empty
  ✓ Compile a rule syntax → it must throw error if resource is empty
  ✓ Compile a rule syntax → it must throw error if action is empty
  ✓ must return expected → when resource have no field
  ✓ must return expected → when resource have single field
  ✓ must return expected → when resource have object field
  ✓ must return expected → when resource have array field

  Tests:    55 passed (88 assertions)
  Duration: 0.06s

## Prosedur testing
1. Jalankan `composer install`
2. Kemudian jalankan `composer test`

Untuk menemukan file testnya, ada di folder tests.
Related to https://github.com/dicoding-dev/dicoding/issues/2727

**Comment by AlexzPurewoko** [comment]
Untuk yang https://github.com/dicoding-dev/abilities-js itu sebenarnya sama ama yang disini sih mas... Semua test corenya sama kecuali yang repository

**Comment by nyangkul** [comment]
di `can() feature function test → it must return false when the user have inverted rule`

Ketika rulesnya aku atur seperti ini, testnya tetap lolos (cek rule id: 2) 

```
$compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope1:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => 'scope1!:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => '!scope1:resource1/[6, 7, 8]:update'
            ],
        ]);
```

Apakah memang diniatkan seperti itu? Harunsy kan `!scope`, ini `scope!`

**Comment by AlexzPurewoko** [comment]
Secara syntax, untuk inverted rules itu ada di awal sintaks sih mas. Jadi untuk yang ID 2, itu kebacanya adalah ability untuk `scope1!` mas @cod3beat

**Comment by nyangkul** [comment]
Ok confirmed kalau begitu @AlexzPurewoko . Tidak ada masalah

**Comment by AlexzPurewoko** [comment]
Siaaap mas @cod3beat... aku eksekusi yah mas yang ada di implementasi dicoding juga

**Comment by nyangkul** [comment]
Usulku untuk rule, model seperti ini tidak diizinkan `!!scope:resource:action`. Alasannya bagi auditor yang akan membaca rule ini, dia bisa terkecoh dengan double negation pada rule di atas. 

Ada beberapa karakter yang seharusnya tidak boleh masuk dalam nama dari tiap segment.

**Comment by nyangkul** [comment]
> Siaaap mas @cod3beat... aku eksekusi yah mas yang ada di implementasi dicoding juga

Ntar ini aku masih review codenya.

**Comment by nyangkul** [comment]
Kalau ada kasus seperti ini, maka hasilnya seperti apa:

```
$compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/[6, 7, 8]:update'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1/[6, 7, 8]:update'
            ],
            (object) [
                'id' => 5,
                'rule' => '!scope2:resource1/7:update'
            ],
        ]);

        $abilityChecker = new AbilityCheckerImpl($compiledRules);
        expect($abilityChecker->can('update', 'resource1', 'scope2', 7))
            ->toBeFalse();
```

Untuk resource 7 ada 2 rule. Nah ketika seperti itu, mana yang didahulukan?

**Comment by AlexzPurewoko** [comment]
> Usulku untuk rule, model seperti ini tidak diizinkan `!!scope:resource:action`. Alasannya bagi auditor yang akan membaca rule ini, dia bisa terkecoh dengan double negation pada rule di atas.
> 
> Ada beberapa karakter yang seharusnya tidak boleh masuk dalam nama dari tiap segment.

Oke mas, aku note dulu yah buat perbaikannya.
List : 
1. Prevent double negation on rule
2. Prevent special characters on scope, resource, and action. (accept : number (0-9), alphabet (a-z), dash (-), underscore (_))

**Comment by AlexzPurewoko** [comment]
> Untuk resource 7 ada 2 rule. Nah ketika seperti itu, mana yang didahulukan?

Dengan rule di ID 5 mas @cod3beat

**Comment by nyangkul** [comment]
Nah kalau seperti itu, ini testnya fail. 

```
$abilityChecker = new AbilityCheckerImpl($compiledRules);
        expect($abilityChecker->can('update', 'resource1', 'scope2', 7))
            ->toBeFalse();
```

**Comment by AlexzPurewoko** [comment]
Iya mas valid... ada bug pas compile rulenya, di mana ia masih menganggap negation itu sebagai bagian dari scope

**Comment by nyangkul** [comment]
Ok aku run through lagi ya. Pelan-pelan baca rulenya. hehe

**Comment by AlexzPurewoko** [comment]
Wait aku juga ada kesalahan penggunaan assertion sih ini mas di pest hehe... toBeString() itu aku kira parameternya buat string yang mau di compare, ternyata itu parameterya buat message error

**Comment by nyangkul** [comment]
Kalau ini bagaimana harusnya hasilnya @AlexzPurewoko ?

```
it('must return true when the rule exactly found on the user abilities', function () {
        $compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/{"author": 667}:update'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1/[6, 7, 8]:*'
            ],
        ]);

        $user = new AbilityCheckerImpl($compiledRules);
        expect($user->hasRule(RuleCompiler::compile('scope2:resource1/[6, 7, 8]:update')))
            ->toBeTrue();
    });
```

Cek rule id 4.

Pas aku jalanin testnya, dia fail

---

**Update**

Padahl ini bisa:

```
it('must return true when the rule exactly found on the user abilities', function () {
        $compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/{"author": 667}:update'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1:update'
            ],
        ]);

        $user = new AbilityCheckerImpl($compiledRules);
        expect($user->hasRule(RuleCompiler::compile('scope2:resource1/[6, 7, 8]:update')))
            ->toBeTrue();
    });
```

**Comment by nyangkul** [comment]
Ini juga seharusnya bagaimana?

```
it('must return true when the rule exactly found on the user abilities', function () {
        $compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/{"author": 667}:update'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1/[6, 7, 8]:*'
            ],
            (object) [
                'id' => 5,
                'rule' => '!scope2:resource1/[6, 7, 8]:update'
            ],
        ]);

        $user = new AbilityCheckerImpl($compiledRules);
        expect($user->hasRule(RuleCompiler::compile('scope2:resource1/[6, 7, 8]:create')))
            ->toBeTrue();
    });
```

Lihat rule 4 dan 5. Pas aku jalanin, testnya gagal

**Comment by nyangkul** [comment]
Ini juga gagal:

```
it('must return true when the rule exactly found on the user abilities', function () {
        $compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/{"author": 667}:*'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1/[6, 7, 8]:*'
            ],
            (object) [
                'id' => 5,
                'rule' => '!scope2:resource1/[6, 7, 8]:update'
            ],
        ]);

        $user = new AbilityCheckerImpl($compiledRules);
        expect($user->hasRule(RuleCompiler::compile('scope1:resource1/{"author": 667}:create')))
            ->toBeTrue();
    });
```

**Comment by AlexzPurewoko** [comment]
> it('must return true when the rule exactly found on the user abilities', function () {
>         $compiledRules = new CompiledRules([
>             (object) [
>                 'id' => 1,
>                 'rule' => 'scope2:resource1:read'
>             ],
>             (object) [
>                 'id' => 2,
>                 'rule' => '!scope1:resource1/666:update'
>             ],
>             (object) [
>                 'id' => 3,
>                 'rule' => 'scope1:resource1/{"author": 667}:update'
>             ],
>             (object) [
>                 'id' => 4,
>                 'rule' => 'scope2:resource1/[6, 7, 8]:*'
>             ],
>         ]);
> 
>         $user = new AbilityCheckerImpl($compiledRules);
>         expect($user->hasRule(RuleCompiler::compile('scope2:resource1/[6, 7, 8]:update')))
>             ->toBeTrue();
>     });

Yang ini harus benar benar match sih mas untuk yang aku buat sekarang... jadi harus match dengan action-nya

**Comment by nyangkul** [comment]
> Yang ini harus benar benar match sih mas untuk yang aku buat sekarang... jadi harus match dengan action-nya

Usulku API nya diubah. Dibuat semacam `hasExactRule`. Karena kalau melihat logika di `can` dan `cannot`, maka ekspektasi `hasRule` juga mirip dengan itu. Menurutmu gimana?

**Comment by AlexzPurewoko** [comment]
Bisa juga sih mas... dan entah kenapa aku juga aga bingung terkait ini juga (sepertinya aku setengah - setengah)
Misalnya ada rule ini : 

scope2:resource1/*:read

Ketika memanggil `hasRule` dengan rule `scope2:resource1/5:read`  kalau menurutku harusnya ini mengembalikan nilai true karena berada dalam cakupan whole attribute dari resource1. 

Dengan adanya ini, berarti baiknya dibuat dua API, yakni `hasRule` dan `hasExactRule` kalau menurutku. Gimana menurutmu mas ?

**Comment by nyangkul** [comment]
Iya mending itu

**Comment by AlexzPurewoko** [comment]
Ok mas... btw aku juga udah update yang bug tadi serta menambahkan beberapa prevention

**Comment by nyangkul** [comment]
Nah ini aku lagi review test di `AbilityRepositoryImplTest`

Ini agak membingungkan di sini. Aku nggak lihat source codenya ya. Murni main2 di test. Aku nggak mengatakan bahwa apa yang aku explore di bawah ini perlu masuk ke codebasenya ya. Tapi ini murni main2 dengan API dan testnya.

Jadi class `StorageFixture` aku kasih 3 capabilities ini:
```
private array $rules = [
        1 => 'scope1:resource1:read',
        2 => 'scope1:resource2:update',
        3 => 'scope3:resource3:*'
    ];
```

Tapi di testnya ini gagal:
```
it('can remove abilities', function () {
        $this->abilityRepositoryInstance->removeAbilities([
            'scope3:resource3:create'
        ]);

        /** @var AbilityChecker $checker */
        $checker = $this->abilityRepositoryInstance->getChecker();
        expect($checker->can('scope3', 'resource3', 'create'))
            ->toBeFalse()
            ->and($checker->can('scope3', 'resource3', 'read'))
            ->toBeTrue() // gagal
            ->and($checker->hasRule('!scope3:resource3:create'))
            ->toBeTrue(); // ini juga gagal
    });
```

Gimana harusnya behaviour di atas?

**Comment by AlexzPurewoko** [comment]
Oh kebalik itu mas susunannya. `can()` method diawali dengan action sih.
```php
$checker->can(action, resource, scope, field);
```

Nah kalau `hasRule()` ini : 
```php
->and($checker->hasRule('!scope3:resource3:create'))
            ->toBeTrue();
```
Ini sudah tepat sih mas, karena rule tersebut memang ngga ada (di hasRule, jika ada inversion, maka akan di ignore).

**Comment by nyangkul** [comment]
Ok aku ubah berarti. gini testnya:

```
it('can remove many abilities', function () {
        $this->abilityRepositoryInstance->removeAbilities([
            'scope1:resource3:create'
        ]);

        /** @var AbilityChecker $checker */
        $checker = $this->abilityRepositoryInstance->getChecker();
        expect($checker->can('create', 'resource3', 'scope1'))
            ->toBeFalse();
    });
```

Itu testnya gagal.

Aslinya rulenya adalah `'scope1:resource3:*'`. Nah kemudian kan aku hapus kemampuan `create` nya.

Jadi harusnya test di atas berjalan dengan sukses

**Comment by AlexzPurewoko** [comment]
Itu rule awalnya berarti begini kah mas @cod3beat ?
`scope1:resource3:*`

Kemudian di remove dengan pass argument `scope1:resource3:create`... Ketika dijalankan begini : 
```php
$checker->can('create', 'resource3', 'scope1');
```

Secara spesifikasi harusnya return true sih... Jadi memang betul test diatas fail, karena harus spesifik semuanya (baik itu action, field, dll) sih mas.

**Comment by nyangkul** [comment]
Nah @AlexzPurewoko , menurutku API nya membuat implementasinya jadi ribet. Karena akhirnya kamu harus membuat code yang mendukung penghapusan capabilities dari tipe all (`*`) menjadi specific. Misalnya yang tadinya all, kemudian dihapus createnya, maka sisa capabilitiesnya apa?

Itu kan ribet. Karena kamu harus bisa mengubah `*` menjadi `create`, `update`, `read`, dst, baru dihapus.

Kalau usulku, hapus API tambah dan hapus capabilities. Sediakan satu API saja, yaitu "set capabilities". Jadi ya sudah, capabilities terbaru adalah sesuai dengan apa yang diberikan ke set capabilities ini.

**Comment by AlexzPurewoko** [comment]
> Misalnya yang tadinya all, kemudian dihapus createnya, maka sisa capabilitiesnya apa?

Kalau berdasarkan spesifikasi sekarang, ia tidak bisa sih mas.

> Kalau usulku, hapus API tambah dan hapus capabilities. Sediakan satu API saja, yaitu "set capabilities".

Opsi yang menarik mas, dan aku pertimbangkan dulu, terutama ketika dealing dengan resource attributenya.

**Comment by AlexzPurewoko** [comment]
Setelah dipertimbangkan, saya setuju sih mas kalau disederhanakan menjadi API set().

Akan tetapi saya mau minta pendapat sih mas tentang behavior-nya. Misalnya ada case si user udah memiliki ability ini : 
`scope:resource/5:*`

Dan si developer ingin set untuk spesifik resource dengan ID 5 dengan hanya aksi read. Maka ability tersebut akan terhapus dan tergantikan dengan ability berikut : 
`scope:resource/5:read`

Seharusnya tepat kan yah mas @cod3beat ?

Kemudian, untuk menghapus ability-nya, kita menyediakan opsi unset().

**Comment by nyangkul** [comment]
@AlexzPurewoko ini yang belum pernah aku lihat adalah gimana kalau actionnya bisa lebih dari 1?

Contoh:
```
scope3:resource3:create,read,delete
```

Nah itu gmn? Bisa nggak?

**Comment by nyangkul** [comment]
> Dan si developer ingin set untuk spesifik resource dengan ID 5 dengan hanya aksi read. Maka ability tersebut akan terhapus dan tergantikan dengan ability berikut :

Nah itu yang sebenarnya mau aku angkat juga @AlexzPurewoko . Apa yang terjadi ketika ada lebih dari 1 rule pada resource yang sama. Gimana cara enginenya menentukan hak akses finalnya.

Kalau dalam kasus di atas, aku setuju hak akses akhirnya untuk resource 5 adalah read. Karena yang lebih spesifik mengalahkan yang general.

**Comment by AlexzPurewoko** [comment]
> Nah itu gmn? Bisa nggak?

Nah kalau ini ngga bisa sih mas.

**Comment by AlexzPurewoko** [comment]
> @AlexzPurewoko ini yang belum pernah aku lihat adalah gimana kalau actionnya bisa lebih dari 1?
> 
> Contoh:
> 
> ```
> scope3:resource3:create,read,delete
> ```
> 
> Nah itu gmn? Bisa nggak?

Ngga bisa sih mas, harus satu persatu

**Comment by AlexzPurewoko** [comment]
> Nah itu yang sebenarnya mau aku angkat juga @AlexzPurewoko . Apa yang terjadi ketika ada lebih dari 1 rule pada resource yang sama. Gimana cara enginenya menentukan hak akses finalnya.

Ada disini sih mas terkait precedence rule nya : 
https://www.notion.so/dicoding/RFC-User-Abilities-f6a25eee6d3e4861aad48abc77815893

**Comment by nyangkul** [comment]
> Akan tetapi saya mau minta pendapat sih mas tentang behavior-nya. Misalnya ada case si user udah memiliki ability ini :
scope:resource/5:*
> 
> Dan si developer ingin set untuk spesifik resource dengan ID 5 dengan hanya aksi read. Maka ability tersebut akan terhapus dan tergantikan dengan ability berikut :
scope:resource/5:read
> 

Ini berarti berbeda dengan precedence rule yang ada di https://www.notion.so/dicoding/RFC-User-Abilities-f6a25eee6d3e4861aad48abc77815893?pvs=4#9ad6ebd1e0864664892e69b0d7fb7798 ya?

**Comment by AlexzPurewoko** [comment]
Itu baru ketika read ability sih mas... Harusnya sih sedikit berbeda...
Ini lagi compose buat set dan unset rule sih mas

**Comment by nyangkul** [comment]
> Itu baru ketika read ability sih mas... Harusnya sih sedikit berbeda...

Maksudnya gmn? Aku belum paham

**Comment by AlexzPurewoko** [comment]
Ini sih mas @cod3beat, precedence rule ketika set ability : 
![image](https://github.com/dicoding-dev/abilities-php/assets/17692360/feaa835e-e2a5-4ca7-a25b-916620f24f7f)

Kalau untuk unset rule, itu nanti ngga ada precedence rulenya, tapi menggunakan metode matcher yang spesifik (untuk sekarang). Misalnya ada rule begini : 

`scope:resource/1:read`

Ketika di unset dengan `scope:resource/1:read` maka akan berhasil. Namun tidak akan melakukan apa apa ketika di unset dengan rule `scope:resource/1:*`

**Comment by AlexzPurewoko** [comment]
Contoh casenya : 

1. Kasus pertama, update dari yang semula bisa melakukan semua action (*) ke yang lebih spesifik.

Rule saat ini : 
```
// ID. RULE
1. scope:resource/123:*
2. scope:resource/4:*
```
Kemudian developer melakukan `set('scope:resource/123:read');`, maka hasil perubahannya adalah : 
```
// ID. RULE
2. scope:resource/4:*
3. scope:resource/123:read
```

2. Kasus kedua, update dari yang semula spesifik, menjadi bisa melakukan semua action (*)

Rule saat ini : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/123:update
3. scope:resource/4:*
```
Kemudian developer melakukan `set('scope:resource/123:*');`, maka hasil perubahannya adalah : 
```
// ID. RULE
3. scope:resource/4:*
4. scope:resource/123:*
```

3. Kasus ketiga, ketika updated action tidak match dengan rule yang ada sekarang.

Rule saat ini : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
```
Kemudian developer melakukan `set('scope:resource/123:update');`, maka hasil perubahannya adalah : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
3. scope:resource/123:update
```

4. Kasus keempat, ketika field attributes tidak match

Rule saat ini : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
```
Kemudian developer melakukan `set('scope:resource/5:*');`, maka hasil perubahannya adalah : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
3. scope:resource/5:*
```

5. Kasus kelima, ketika memiliki kesamaan action dan field attributes, namun berbeda dalam case inverted rule (yang di update itu rulenya inverted, atau sebaliknya).

Rule saat ini : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
```
Kemudian developer melakukan `set('!scope:resource/123:read');`, maka hasil perubahannya adalah : 
```
// ID. RULE
2. scope:resource/4:*
3. !scope:resource/123:read
```

6. Kasus keenam, ketika rulenya sama persis, maka tidak akan terjadi aksi apapun.

Rule saat ini : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
```
Kemudian developer melakukan `set('scope:resource/123:read');`, maka hasil perubahannya adalah : 
```
// ID. RULE
1. scope:resource/123:read
2. scope:resource/4:*
```

**Comment by nyangkul** [comment]
Ketentuan di atas sudah diimplementasikan di codebasenya?

**Comment by AlexzPurewoko** [comment]
> Ketentuan di atas sudah diimplementasikan di codebasenya?

Belum mas, lagi konsep

**Comment by AlexzPurewoko** [comment]
Berarti oke kan mas @cod3beat ? saya implementasikan kalau gitu hehe

**Comment by nyangkul** [comment]
ok @AlexzPurewoko

**Comment by AlexzPurewoko** [comment]
Sudah kuupdate lagi yah mas @cod3beat...

   PASS  Tests\Feature\Core\AbilityCheckerImplTest
  ✓ can() feature function test → it must return false when the user have inverted rule
  ✓ can() feature function test → it must return true when user have rule with ALL action
  ✓ can() feature function test → it must return true when the rule is matched with user abilities
  ✓ can() feature function test → it must return false when the rule is unmatched with user abilities
  ✓ cannot() feature function test → it must return true when the user cannot access the resource
  ✓ hasRule() feature function test → it must return true when the rule exactly found on the user abilities
  ✓ hasRule() feature function test → it must return false when the rule is not found on the user abilities

   PASS  Tests\Feature\Core\Repository\AbilityRepositoryImplTest
  ✓ Get Ability Checker Function Test → it must return ability checker…  0.01s  
  ✓ Set the ability test → it can set the ability from whole action (star) to specific action
  ✓ Set the ability test → it can set the ability from specific action to whole action (star) action
  ✓ Set the ability test → it must add new ability when the scope, resource and field attributes is matched, but not match with the action
  ✓ Set the ability test → it must add new ability when the field attributes is not match
  ✓ Set the ability test → it can invert the matched rules, when it is not inverted yet
  ✓ Set the ability test → when the rule is not updated
  ✓ Unset the ability test → it must delete the ability when the rule is matched exactly
  ✓ Unset the ability test → it must not remove the ability when the rule is unmatched

   PASS  Tests\Unit\Core\Objects\ActionTest
  ✓ it must fail when assigned with empty value                          0.01s  
  ✓ it must throw error when passing invalid action name
  ✓ it must throw error when passing more than one star action
  ✓ Must use star symbol when using default argument
  ✓ Successfully define specific action
  ✓ it can know if the action is whole action (star)

   PASS  Tests\Unit\Core\Objects\CompiledRulesTest
  ✓ Compile and query rules → it must return empty if scope does not found with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return empty if resource does not found with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return empty if action does not found with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return all rule when action is unspecified with (Abilities\Core\Objects\CompiledRules)
  ✓ Compile and query rules → it must return expected rule id with (Abilities\Core\Objects\CompiledRules)

   PASS  Tests\Unit\Core\Objects\ResourceTest
  ✓ it must throw error when passing empty/blank argument on 'resource'
  ✓ it must throw error when passing invalid resource name
  ✓ toString function test → successfully encode without field
  ✓ toString function test → successfully encode with array field
  ✓ toString function test → successfully encode with json object field
  ✓ toString function test → successfully encode with non json field
  ✓ allField() function test → it must return true when field property is empty
  ✓ allField() function test → it must return true when field property is star
  ✓ allField() function test → it must return false when field property is neither star and empty
  ✓ matchField() function test → it must return true if the resource rule has star field
  ✓ matchField() function test → it must return false if the argument is empty
  ✓ matchField() function test → it must return true if match the single field
  ✓ matchField() function test → it must return false if fields does not contains the field argument
  ✓ matchField() function test → it must return true if fields contains the field argument
  ✓ matchField() function test → it must return true if fields contains exactly one field argument
  ✓ matchField() function test → it must return true if field object match exactly with argument
  ✓ matchField() function test → it must return false if field object doesnt match exactly with argument
  ✓ isEqualWith() function test → it must return false when resource name is different
  ✓ isEqualWith() function test → it must return false when resource field type is different
  ✓ isEqualWith() function test → it must return true when both resources have star field
  ✓ isEqualWith() function test → it must return false when both resources have different singular field
  ✓ isEqualWith() function test → it must return true when both resources have same singular field value
  ✓ isEqualWith() function test → it must return false when both resources have different array field
  ✓ isEqualWith() function test → it must return true when both resources have same array field
  ✓ isEqualWith() function test → it must return false when both resources have different object field
  ✓ isEqualWith() function test → it must return true when both resources have same object field

   PASS  Tests\Unit\Core\Objects\RuleTest
  ✓ getRuleId function test → it must throw error when not calling setRuleId beforehand
  ✓ getRuleId function test → it returns expected ruleId
  ✓ toString function test → successfully encode inverted rules
  ✓ toString function test → successfully encode normal rules
  ✓ toString function test → successfully rule with custom resource

   PASS  Tests\Unit\Core\Objects\ScopeTest
  ✓ it must throw error when passing empty/blank argument on 'scope'
  ✓ it must throw error when passing invalid scope name
  ✓ Must use 'global' when using default argument
  ✓ Successfully define specific action

   PASS  Tests\Unit\Core\RuleCompilerTest
  ✓ Compile a rule syntax → it must throw error if syntax is empty
  ✓ Compile a rule syntax → it must throw error if scope is empty
  ✓ Compile a rule syntax → it must throw error if resource is empty
  ✓ Compile a rule syntax → it must throw error if action is empty
  ✓ must return expected → inverted rules
  ✓ must return expected → when resource have no field
  ✓ must return expected → when resource have single field
  ✓ must return expected → when resource have object field
  ✓ must return expected → when resource have array field

  Tests:    71 passed (109 assertions)
  Duration: 0.08s

**Comment by AlexzPurewoko** [comment]
Mas @cod3beat, kalau yang checker `can` dan `cannot` itu seharusnya udah aman kan ya?

**Comment by nyangkul** [comment]
Aku nemu failing test ini @AlexzPurewoko . Aku sedikit ubah fixturenya:

```
it('must return true when the rule is matched with user abilities', function () {
        $compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/[6, 7, 8]:update'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1/[6, 7, 8]:update'
            ],
            (object) [
                'id' => 5,
                'rule' => '!scope2:resource1:*'
            ],
        ]);

        $abilityChecker = new AbilityCheckerImpl($compiledRules);
        expect($abilityChecker->can('update', 'resource1', 'scope2', 7))
            ->toBeTrue();
    });
```
Test di atas gagal. Cek rule id 4 & 5.

Itu harusnya true atau false?

**Comment by AlexzPurewoko** [comment]
> Test di atas gagal. Cek rule id 4 & 5.
> 
> Itu harusnya true atau false?

Harusnya false mas. Karena dia sudah di invert pada rule dengan ID 5. Inverted rule itu ada pada kedudukan pertama pengecekan sih mas

**Comment by nyangkul** [comment]
nah itu bug berarti ya?

**Comment by AlexzPurewoko** [comment]
> nah itu bug berarti ya?

Ngga mas, memang seperti itu sih.

**Comment by nyangkul** [comment]
Hmm... ok kamu coba lanjut aja. ntar aku explore case dimana invert ini menjadi rule pertama

**Comment by AlexzPurewoko** [comment]
Shaap mas

**Comment by nyangkul** [comment]
Nemu kasus ini gimana @AlexzPurewoko ? Cek rule 5, 6, 7

```
it('must return false when the user have inverted rule', function () {
        $compiledRules = new CompiledRules([
            (object) [
                'id' => 1,
                'rule' => 'scope2:resource1:read'
            ],
            (object) [
                'id' => 2,
                'rule' => '!scope1:resource1/666:update'
            ],
            (object) [
                'id' => 3,
                'rule' => 'scope1:resource1/[6, 7, 8]:update'
            ],
            (object) [
                'id' => 4,
                'rule' => 'scope2:resource1/[6, 7, 8]:update'
            ],
            (object) [
                'id' => 5,
                'rule' => 'scope2:resource1:*'
            ],
            (object) [
                'id' => 6,
                'rule' => '!scope2:resource1/7:*'
            ],
            (object) [
                'id' => 7,
                'rule' => 'scope2:resource1/7:update'
            ],
        ]);

        $abilityChecker = new AbilityCheckerImpl($compiledRules);
        expect($abilityChecker->can('update', 'resource1', 'scope2', 7))
            ->toBeFalse();
    });
```

Ini tesnya gagal

**Comment by AlexzPurewoko** [comment]
Harusnya berhasil itu mas... Sorry ternyata pas di awal itu aku querynya langsung specific action, jadi yang '*' (whole action) ini ngga terdeteksi. 

Thank you mass....

Sudah aku update lagi mas @cod3beat. Silakan pull kembali

**Comment by nyangkul** [comment]
~Setiap kali ada bug seperti ini, sebaiknya kamu buatkan test casenya juga @AlexzPurewoko~

Oh maaf, sudah kamu buatkan ya. Sip sip

**Comment by nyangkul** [comment]
Ok @AlexzPurewoko . Dari aku insyallah sudah beres ini. Semangat semangat

**Comment by AlexzPurewoko** [comment]
Okaay mas @cod3beat, terimakasih atas bantuannyaa yaa... Aku close dulu ini, nanti kalau ada lagi aku buka issue baru
